FROM almalinux:9
LABEL Course="DevOps with Docker" \
      Module="Dockerfiles" \
      Topic="LABEL" \
      Description="This Dockerfile demonstrates the use of LABEL instruction to add metadata to the image." \
      Author="DAWS" \
      Version="1.0"
