FROM almalinux:9
ENV COURSE="DevOps with Docker" \
      MODULE="Dockerfiles" \
      TOPIC="FROM" \
      DESCRIPTION="This Dockerfile demonstrates the use of FROM instruction to specify the base image." \
      AUTHOR="DAWS" \
      VERSION="1.0"
CMD ["sleep", "1000"]
